POST / HTTP/1.1
Host: handler.example.com
Content-Type: application/xml
Content-Length: 24
ce-specversion: 0.4-wip
ce-id: 123
ce-source: https://cloudevents.io/contenttype
ce-type: io.cloudevents.contenttype-test

<much wow="xml"/>