POST / HTTP/1.1
Host: handler.example.com
Content-Length: 0
ce-specversion: 0.4-wip
ce-id: %22%F0%9F%98%89%03%3c.is%2BFine%E7%81%AB%22
ce-source: https://cloudevents.io/unicode-strings
ce-type: %22%F0%9F%98%89%03%3c.is%2BFine%E7%81%AB%22
ce-subject: %22%F0%9F%98%89%03%3c.is%2BFine%E7%81%AB%22

