name: verify
on: [push, pull_request]
jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "tools/requirements.txt"
      - name: Install tools dependencies
        run: python -m pip install -r tools/requirements.txt
      - name: Test Tools
        run: make -f tools/Makefile test_tools
      - name: Verify Specification
        run: make -f tools/Makefile verify
